### ISSUE TITLE
Add DCAS REST endpoint(s)

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#169]
DCAS endpoint(s) should be exposed such that clients may retrieve Sidetree anchor, map, and batch files in order to verify SIdetree documents.

**Comment by troyronda** [comment]
Notes: 

- endpoints will be based on configuration such that we can configure which channels / collections are exposed via REST APIs.
- should also define roles/config to control which peers actually expose these endpoints.
