### ISSUE TITLE
undefined: roles.SetRoles

### ISSUE THREAD

**Issue by rockyhwang** [trustbloc/sidetree-fabric#384]
The error occurred on role_test.go
Not sure the import package should be "role" or "roles"

{
	"resource": "/home/rocky/go/projects/TWCC_Block/sidetree-fabric/pkg/role/role_test.go",
	"owner": "go",
	"severity": 8,
	"message": "undefined: roles.SetRoles",
	"source": "go",
	"startLineNumber": 61,
	"startColumn": 3,
	"endLineNumber": 61,
	"endColumn": 25
}

**Comment by bstasyszyn** [comment]
@rockyhwang you need to set the Go tag: -tags testing
