### ISSUE TITLE
Implement Sidetree REST APIs in the peer

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#66]
Currently the integration tests run with an external Sidetree container that implements the REST APIs. The REST APIs should be implemented in the peer process so that the external container is no longer necessary.

**Comment by troyronda** [comment]
It would also make sense to create a restapi package in sidetree-core-go that relies on swagger annotations (instead of generated code).

See aries-framework-go version here: https://github.com/hyperledger/aries-framework-go/tree/master/pkg/restapi
